-- MySQL Script generated by MySQL Workbench
-- 09/27/16 13:51:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema locacao_veiculos_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema locacao_veiculos_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `locacao_veiculos_db` DEFAULT CHARACTER SET utf8 ;
USE `locacao_veiculos_db` ;

-- -----------------------------------------------------
-- Table `locacao_veiculos_db`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao_veiculos_db`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preco` DECIMAL(18,2) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locacao_veiculos_db`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao_veiculos_db`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(50) NULL,
  `endereco` VARCHAR(50) NULL,
  `telefone` VARCHAR(14) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locacao_veiculos_db`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao_veiculos_db`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `endereco` VARCHAR(50) NULL,
  `telefone` VARCHAR(14) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locacao_veiculos_db`.`avaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao_veiculos_db`.`avaria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(18,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locacao_veiculos_db`.`multa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao_veiculos_db`.`multa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(18,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locacao_veiculos_db`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao_veiculos_db`.`veiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `ano` INT NULL,
  `valor` DECIMAL(18,2) NULL,
  `observacao` VARCHAR(50) NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_veiculo_categoria_idx` (`categoria_id` ASC),
  CONSTRAINT `fk_veiculo_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `locacao_veiculos_db`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locacao_veiculos_db`.`locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao_veiculos_db`.`locacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME(8) NULL,
  `veiculo_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `funcionario_id_cad` INT NOT NULL,
  `funcionario_id_rec` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_locacao_veiculo1_idx` (`veiculo_id` ASC),
  INDEX `fk_locacao_cliente1_idx` (`cliente_id` ASC),
  INDEX `fk_locacao_funcionario1_idx` (`funcionario_id_cad` ASC),
  INDEX `fk_locacao_funcionario2_idx` (`funcionario_id_rec` ASC),
  CONSTRAINT `fk_locacao_veiculo1`
    FOREIGN KEY (`veiculo_id`)
    REFERENCES `locacao_veiculos_db`.`veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locacao_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `locacao_veiculos_db`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locacao_funcionario1`
    FOREIGN KEY (`funcionario_id_cad`)
    REFERENCES `locacao_veiculos_db`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locacao_funcionario2`
    FOREIGN KEY (`funcionario_id_rec`)
    REFERENCES `locacao_veiculos_db`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locacao_veiculos_db`.`locacao_avaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao_veiculos_db`.`locacao_avaria` (
  `locacao_id` INT NOT NULL,
  `avaria_id` INT NOT NULL,
  PRIMARY KEY (`locacao_id`, `avaria_id`),
  INDEX `fk_locacao_avaria_avaria1_idx` (`avaria_id` ASC),
  CONSTRAINT `fk_locacao_avaria_locacao1`
    FOREIGN KEY (`locacao_id`)
    REFERENCES `locacao_veiculos_db`.`locacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locacao_avaria_avaria1`
    FOREIGN KEY (`avaria_id`)
    REFERENCES `locacao_veiculos_db`.`avaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locacao_veiculos_db`.`locacao_multa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao_veiculos_db`.`locacao_multa` (
  `multa_id` INT NOT NULL,
  `locacao_id` INT NOT NULL,
  PRIMARY KEY (`multa_id`, `locacao_id`),
  INDEX `fk_locacao_multa_locacao1_idx` (`locacao_id` ASC),
  CONSTRAINT `fk_locacao_multa_multa1`
    FOREIGN KEY (`multa_id`)
    REFERENCES `locacao_veiculos_db`.`multa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locacao_multa_locacao1`
    FOREIGN KEY (`locacao_id`)
    REFERENCES `locacao_veiculos_db`.`locacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
